indent-width = 2

select = [
  "F",
  "W6",
  "E71",
  "E72",
  "E112",
  "E113",
  # "E124",
  "E203",
  "E272",
  # "E303",
  # "E304",
  "E501",
  # "E502",
  "E702",
  "E703",
  "E731",
  "W191",
  "W291",
  "W293",
  "UP039",  # unnecessary-class-parentheses
]

line-length = 150

exclude = [
  "disassemblers/",
  "docs/",
  "examples/",
  "extra/",
  "openpilot/",
  "tinygrad/runtime/autogen",
]

